# Generated by Django 4.1.5 on 2023-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=models.Index(fields=['name'], name='datarepo_in_name_2d294d_idx'),
        ),
    ]
