# Generated by Django 4.1.5 on 2023-02-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0005_product_datarepo_pr_name_e6d26a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='datarepo_pr_name_e6d26a_idx',
        ),
    ]
