# Generated by Django 4.1.5 on 2023-02-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0007_product_datarepo_pr_name_e6d26a_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
